### ISSUE TITLE
Ansible-Galaxy installs deprecated Version of php_roles packages

### ISSUE THREAD

**Issue by robinduerhager** [geerlingguy/ansible-collection-php#9]
## Description
When installing the php_roles collection, at least `geerlingguy.php_roles.php_versions` has a version mismatch with `geerlingguy.php_versions`. E.g.: The collection version tries to enable `PowerTools` on Rocky Linux 8, even though it has to be `powertools` for now (which is fixed in the current version).

## Reproduction steps
1. run `ansible-galaxy collection install geerlingguy.php_roles`
2. run `ansible-galaxy install geerlingguy.php-versions`
3. compare `/root/.ansible/roles/geerlingguy.php-versions/tasks/setup-RedHat.yml` and `/root/.ansible/collections//geerlingguy.php-versions/tasks/setup-RedHat.yml`

The files should respectively look like this:
```yml
# /root/.ansible/collections/ansible_collections/geerlingguy/php_roles/roles/php_versions/tasks/setup-RedHat.yml
- name: Enable DNF module for CentOS 8+.
    shell: |
      dnf config-manager --set-enabled PowerTools
      dnf module enable -y php:remi-{{ php_version }}

# /root/.ansible/roles/geerlingguy.php-versions/tasks/setup-RedHat.yml
- name: Enable DNF module for CentOS 8+.
    shell: |
      dnf config-manager --set-enabled powertools
      dnf module enable -y php:remi-{{ php_version }}
```
